apiVersion: v1
name: lighthouse-webui-plugin
description: Web UI for Lighthouse, to visualize events, jobs, and merge status/history.
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
home: https://github.com/jenkins-x-plugins/lighthouse-webui-plugin
version: 0.0.3
appVersion: 0.0.3
sources:
  - https://github.com/jenkins-x-plugins/lighthouse-webui-plugin
